name: 'mdc'
version: 0.0.1
description: Material Components for the web (MDC-Web).
author: Adao Junior
homepage: https://github.com/dart-league/mdc

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
